const Products = [
  {
    id: 1,
    image: "",
    shippingWeight: 7,
    type: "FLOWER",
    name: "2 Oz Deal Watermelon Zkittles + Purple Gushers",
    star: 4.6,
    reviews: 135,
    optional_addon: "Sativa 100%",
    price: 80.0,
    sizes: ["28g", "1/2lb", "1/4lb"],
    in_stock: false,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
  {
    id: 2,
    image: "",
    shippingWeight: 23,
    type: "Type B",
    name: "Product 2",
    star: 3.2,
    reviews: 50,
    optional_addon: "Add on 2",
    price: 5.99,
    old_price: "$200.00",
    sizes: ["Small", "Large"],
    in_stock: true,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
  {
    id: 3,
    image: "",
    shippingWeight: 11,
    type: "Type A",
    name: "Product 3",
    star: 4.8,
    reviews: 150,
    optional_addon: "Add-on 3",
    price: 15.99,
    old_price: "$200.00",
    sizes: ["Medium"],
    in_stock: true,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
  {
    id: 4,
    image: "",
    shippingWeight: 22,
    type: "Type C",
    name: "Product 4",
    star: 4.0,
    reviews: 75,
    optional_addon: "Add-on 4",
    price: 8.99,
    old_price: "$200.00",
    sizes: ["Small", "Medium"],
    in_stock: false,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
  {
    id: 5,
    image: "",
    shippingWeight: 20,
    type: "Type B",
    name: "Product 5",
    star: 3.5,
    reviews: 30,
    optional_addon: "Add-on 5",
    price: 6.99,
    old_price: "$200.00",
    sizes: ["Large"],
    in_stock: true,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
  {
    id: 6,
    image: "",
    shippingWeight: 22,
    type: "Type A",
    name: "Product 6",
    star: 4.2,
    reviews: 90,
    optional_addon: "Add-on 6",
    price: 12.99,
    old_price: "$200.00",
    sizes: ["Small", "Medium"],
    in_stock: true,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
  {
    id: 7,
    image: "",
    shippingWeight: 30,
    type: "Type C",
    name: "Product 7",
    star: 4.1,
    reviews: 60,
    optional_addon: "Add-on 7",
    price: 7.99,
    old_price: "$200.00",
    sizes: ["Small"],
    in_stock: false,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
  {
    id: 8,
    image: "",
    shippingWeight: 50,
    type: "Type B",
    name: "Product 8",
    star: 3.8,
    reviews: 45,
    optional_addon: "Add-on 8",
    price: 9.99,
    old_price: "$200.00",
    sizes: ["Small", "Large"],
    in_stock: false,
    description:
      "Jungle Diamonds is a slightly indica dominant hybrid strain (60% indica/40% sativa) created through crossing the infamous Slurricane X Gorilla Glue #4 strains.",
  },
];

export default Products;
